---
# `filebeat_config` is templated directly into filebeat.yml for the config.
# You are expected to override this variable, as these configurations are
# only suited for development purposes.
# See https://github.com/elastic/filebeat/blob/master/etc/filebeat.yml for
# an exhaustive list of configurations.
filebeat_config:
  filebeat:
    prospectors:
      - paths:
          - /var/log/*.log
          - /var/log/nova/nova-compute.log
          - /var/log/nova/nova-manage.log
          - /var/log/ceilometer/ceilometer-agent-compute.log
          - /var/log/neutron/neutron-netns-cleanup.log
          - /var/log/neutron/openvswitch-agent.log
          - /var/log/neutron/ovs-cleanup.log
          - /var/log/cinder/cinder-volume.log
        input_type: log
  output:
    logstash:
      hosts:
        - localhost.localdomain:5044
  logging:
    file:
      rotateeverybytes: 10485760

# The installation state of the filebeat package, passed to the appropriate
# packaging module (yum/apt) as the 'state'.
# Set to 'latest' to upgrade.
filebeat_package_state: present
